<?php
$section = $section ?? 'Overview';
$back = '/super-admin';
$pdo = Database::pdo();
$rows = [];
if ($section === 'PG Owners') $rows = $pdo->query('SELECT full_name, email, is_active FROM users WHERE role = "pg_owner" ORDER BY created_at DESC')->fetchAll();
if ($section === 'PGs') $rows = $pdo->query('SELECT name, city, area, is_approved, is_active FROM pgs ORDER BY created_at DESC')->fetchAll();
if ($section === 'Bookings') $rows = $pdo->query('SELECT bookings.status, bookings.monthly_amount, pgs.name AS pg_name, users.full_name FROM bookings JOIN pgs ON pgs.id = bookings.pg_id JOIN users ON users.id = bookings.student_id ORDER BY bookings.created_at DESC')->fetchAll();
if ($section === 'Payments') $rows = $pdo->query('SELECT payments.amount, payments.status, payments.due_date, pgs.name AS pg_name FROM payments JOIN bookings ON bookings.id = payments.booking_id JOIN pgs ON pgs.id = bookings.pg_id ORDER BY payments.created_at DESC')->fetchAll();
?><!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($section) ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>body{background:#f5f7ff;color:#111827}.app-shell{display:flex;min-height:100vh}.sidebar{width:260px;min-width:260px;background:linear-gradient(180deg,#111827 0%,#1f2937 100%);color:white;padding:24px 18px;position:sticky;top:0;height:100vh}.brand{display:flex;align-items:center;gap:12px;padding:8px 10px 20px;border-bottom:1px solid rgba(255,255,255,.08)}.brand-badge{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:rgba(255,255,255,.14)}.brand h4{margin:0;font-size:1.1rem}.nav-menu{margin-top:24px;display:grid;gap:8px}.nav-item{display:flex;align-items:center;gap:12px;padding:12px 14px;border-radius:14px;color:rgba(255,255,255,.8);text-decoration:none;font-weight:600}.nav-item.active,.nav-item:hover{background:rgba(255,255,255,.12);color:#fff}.content{flex:1;min-width:0}.page{max-width:1100px;margin:0 auto;padding:32px 18px}.panel{background:#fff;border:1px solid rgba(15,23,42,.08);border-radius:22px;padding:22px;box-shadow:0 18px 30px rgba(15,23,42,.05)}.table{vertical-align:middle}@media(max-width:760px){.sidebar{width:220px;min-width:220px;padding:18px 12px}.page{padding:20px 12px}}</style></head>
<body><div class="app-shell"><?php include BASE_PATH . '/app/views/partials/admin-sidebar.php'; ?><main class="content"><div class="page"><div class="d-flex justify-content-between align-items-center mb-4"><div><div class="text-primary fw-bold">Super Admin</div><h1 class="mb-0"><?= e($section) ?></h1></div><a class="btn btn-outline-dark" href="<?= $back ?>">Dashboard</a></div><div class="panel"><?php if (in_array($section, ['Reports', 'Settings'], true)): ?><div class="p-4 bg-light rounded-4"><h4><?= e($section) ?> workspace</h4><p class="text-secondary mb-0"><?= $section === 'Reports' ? 'Platform reporting is ready for export integrations.' : 'Platform settings are managed securely from this workspace.' ?></p></div><?php elseif (!$rows): ?><p class="text-secondary mb-0">No records available yet.</p><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><?php foreach (array_keys($rows[0]) as $heading): ?><th><?= e(ucwords(str_replace('_', ' ', $heading))) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><?php foreach ($row as $value): ?><td><?= e((string) $value) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></main></div></body></html>
